#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#

if ! grep -Po amulet <<< $I &> /dev/null; then
    printf "\n"
    echo "Вы нашли изумрудный **амулет**!"
    printf "\n"
    echo "Чтобы собрать сокровища, вам нужно создать переменную для хранения инвентаря."
    printf "\n"
    echo "Создайте переменную и добавьте ваше сокровище в нее так:"
    printf "\n"
    echo "export I=amulet,\$I"
    printf "\n"
    echo "Вы всегда можете проверить свое богатство с помощью этой команды:"
    printf "\n"
    echo "echo \$I"
    printf "\n"
    mv ../.chapel ../chapel 2>/dev/null
    mv ../.vault ../vault 2>/dev/null
    mv ../.scrap ../scrap 2>/dev/null
else
    echo "Это сокровище уже взято."
fi


















































































































































































































































































# Hmm, that didn't work.
# Try moving into the armoury, maybe you
# can come back to this treasure later!
