#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
echo "В углу стоит разлагающийся старый алтарь забытого бога."
printf "\n"
echo "На земле лежит маленькая безделушка."
echo "Она выглядит религиозной по своей природе."
echo "Хотите ли вы положить безделушку обратно на алтарь?"
printf "\n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "Вы кладете безделушку на алтарь."
   echo "Вы чувствуете, как нежный ветерок проходит через комнату."
   touch .bless
else
   echo "Хотите ли вы забрать безделушку себе?"
   read RESP
   if [ $RESP = "y" -o $RESP = "Y" ]; then
       echo "Не забудьте добавить безделушку в ваш инвентарь!"
       touch .curse
   else
   echo "Вы оставляете безделушку там, где она лежит."
   echo "Здесь великая печаль."
   echo "Вы чувствуете, что должны двигаться дальше."
   touch .curse
   fi
fi



















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a *
# it means they are applications.
# Try this:
#
# ./altar
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F
