#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#


echo "Вы нашли бутылку с зельем, в котором сверкает зеленая жидкость. Хотите ли вы выпить его?"
printf "\n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "Вкус зеленого растения заполняет ваш рот."
   echo "Оно согревает и укрепляет вас."
   printf "\n"
   echo "Создайте переменную для ваших очков здоровья (HP)."
   echo "У вас 15 HP:"
   echo "$ export HP=15"
   printf "\n"
else
   echo "Вы не родились вчера;"
   echo "это зелье, вероятно, яд."
   printf "\n"
   echo "Создайте переменную для ваших очков здоровья (HP)."
   echo "У вас 10 HP:"
   echo "$ export HP=10"
   printf "\n"
fi

echo "Вы можете проверить ваше здоровье в любой момент:"
printf "\n"
echo "echo \$HP"
printf "\n"
mv ../../.chapel ../../chapel 2>/dev/null
mv ../../.vault ../../vault 2>/dev/nul




















































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a *
# it means they are applications.
# Try this:
#
# ./potion
