#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
printf "\n"
echo "Вы нашли блестящий серебряный **меч**!"
echo "Вы восхищаетесь его мастерством, и вам вспоминаются"
echo "истории из вашего детства о великом"
echo "мистическом короле Раннисмире, который носил такой меч,"
echo "чтобы защищать королевство от нежити."
printf "\n"
echo "Добавьте этот предмет в ваш инвентарь:"
printf "\n"
echo "$ export I=sword,\$I"
printf "\n"
echo "Помните, вы можете проверить ваш инвентарь:"
printf "\n"
echo "echo \$I"
printf "\n"
mv ../../.chapel ../../chapel 2>/dev/null
mv ../../.vault ../../vault 2>/dev/null
mv ../../.scrap ../../scrap 2>/dev/null

























































































































































































































































































# Hmm, that didn't work!
#
# Maybe the scroll can provide a clue.
