#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
gameover () {
    echo "Вы видите труп убитого приключенца на полу подземелья." > corpse
    echo "Вы находите следующие предметы на трупе:  " >> corpse
    echo >> corpse
    echo $I >> corpse
    curr=`basename $PWD`
    while [ "$curr" != "entrance" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}
roll() {
    echo "Введите число."
    read NUM
    ALPHA=$RANDOM
    OMEGA=$RANDOM
    A=`echo $ALPHA | cut -b 1-2`
    O=`echo $OMEGA | cut -b 1-2`
    let "NUM=$ALPHA % $OMEGA"
    MONSTER=$RANDOM
    MONSTER=`echo $MONSTER | cut -b 1-2`
    NUM=`echo $NUM | cut -b 1-2`
    echo "Монстр выбросил " $MONSTER
    echo "Вы выбросили " $NUM
    resolve
}

resolve() {
    if ! grep -Po 'sword' <<< $I &> /dev/null; then
        echo "У вас нет меча!"
        echo
        echo "Ваши атаки будут менее эффективными."
        let NUM=NUM-10
    fi
    if [[ $MONSTER -eq $NUM ]]; then
        echo "Вы и монстр парируете атаки друг друга."
        echo "Бросьте снова..."
        roll
    fi

    if [[ $MONSTER -lt $NUM ]]; then
       echo "Попадание! Точное попадание!"
       echo "Вы убили чудовище."
       echo '#!/bin/bash
             if ! grep -Po crown <<< $I &> /dev/null; then
                 echo "Вы нашли *корону*!"
                 echo "Добавьте её в ваш инвентарь."
             else
                 echo "Это сокровище уже взято."
            fi' > treasure
       chmod +x treasure
       mv monster carcass
    else
        echo "Ваша атака отражена с кожаного тела монстра."
        echo "Вы получаете 5 урона. Отнимите это от ваших HP."
        echo 'let "HP=HP-5"'
        let HP=HP-5
        export HP
        if [ "$HP" -le 0 ]; then
            echo "Вы были убиты монстром."
            echo
            echo "ИГРА ОКОНЧЕНА!"
            gameover
            exit 1
        fi
        printf "\n"
        roll
    fi
}

if [ "$0" = "./carcass" ]; then
    echo "Вы находите труп зловещего чудовища."
    echo
    echo "В его останках ничего интересного."
    exit 0
fi

echo "Крепкое чудовище с тремя ногами, полное клыков"
echo "и с бархатным хвостом и 8 руками медленно приближается к вам."
printf "\n"
echo "Если у вас есть меч, вы можете атаковать."
echo "Если нет, лучше бежать."
echo "Хотите атаковать? y/n"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ];then
    roll
else
    echo "Вы разумно поворачиваетесь и убегаете."
    echo "Быстро перейдите в предыдущую директорию."
fi
printf "\n"

#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
##
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Well that didn't work!
