#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#

echo "Руны, язык древних мистиков, которые когда-то правили"
echo "этой землей, вырезаны на западной стене."
echo "Хотите ли вы их прочитать?"
read RESP
if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "Вы вспоминаете уроки Кейтилин Зеленой,"
   echo "которая обучила вас этим древним буквам."
   printf "\n"
   echo "Руны — это инструкции о том, как вызвать"
   echo "портал, который позволит вам пройти через"
   echo "невидимую дверь, скрытую в стене."
   printf "\n"
   echo "В Bash, символьная ссылка — это *псевдоним* или *ярлык*"
   echo "для другого файла или директории."
   echo "Создайте одну из этой комнаты в соседнюю:"
   echo "ln -f -s `pwd`/../../../chapel/courtyard/aviary/hall portal"
   printf "\n"
else
   echo "Вы решаете, что, вероятно, лучше оставить"
   echo "магические надписи как есть."
fi



























































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a *
# it means they are applications.
# Try this:
#
# ./spell
