#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
gameover () {
    echo "Вы видите труп убитого приключенца на полу подземелья." > corpse
    echo "Вы находите следующие предметы на трупе:  " >> corpse
    echo >> corpse
    echo $I >> corpse
    curr=`basename $PWD`
    while [ "$curr" != "entrance" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}

if [ "$0" = "./pieces" ]; then
    echo "Вы перебираете куски разрушенной статуи."
    echo
    echo "Вы не находите ничего интересного среди останков статуи."
    exit 1
fi

echo "В углу комнаты стоит грубая статуя."
echo "Подходите ли вы к ней?"
read RESP

if [ $RESP = "y" -o $RESP = "Y" ]; then
   echo "Статуя оживает, гремит:"
   echo '"КТО ОСМЕЛИВАЕТСЯ ВТОРГАТЬСЯ В ПАЛАТУ ДУХОВ?"'
   printf "\n"
   echo "Она с силой бросает кулак в вашу сторону, нанося вам 5 урона."
   echo "Отнимите 5 от ваших HP:"
   echo 'let "HP=HP-5"'
   let HP=HP-5
   export HP
   if [ "$HP" -le 0 ]; then
        echo "Вы были убиты статуей."
        echo
        echo "ИГРА ОКОНЧЕНА!"
        gameover
        exit 1
   fi
   sed -i 's/coins/diamonds/g' ./treasure
   printf "\n"
   echo "У вас есть меч?"
   read RESP
   if [ $RESP = "y" -o $RESP = "Y" ]; then
       if grep -Po 'sword' <<< $I &> /dev/null; then
           echo "Вы убили статую!"
           mv statue pieces
       else
           printf "\n"
           echo "Нет, у вас его нет!"
           echo 'Беги!'
           rm treasure
           rm spell
      fi
   else
       echo "Беги!"
   fi
else
    echo "Вы осторожно избегаете статуи,"
    echo "вспоминая истории о живом камне"
    echo "ждущем своей жертвы, глубоко в пугающих катакомбах."
   printf "\n"
fi











































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a *
# it means they are applications.
# Try this:
#
# ./statue
