#!/bin/bash
#
# If you are reading this, you have wandered out of bounds
# and are reading the code that drives the game.
#
#                    Congratulations!
#
# Learning Linux is all about curiosity, so read this code and see
# if you can figure out what it does.
#
# When you're ready to continue playing the game, though, stick to
# the scrolls. If you're stuck, go to Gitlab and create an issue.
# We're happy to provide hints.
#
echo
if ! grep -Po coins <<< $I &> /dev/null; then
    echo "Вы нашли запас **монет**!"
    echo "Они старые и потертые временем,"
    echo "но все еще блестят в магическом свете,"
    echo "исходящем от ваших глаз."
    printf "\n"
    echo "Добавьте этот предмет в ваш инвентарь:"
    printf "\n"
    echo '$ export I=coins,$I'
    printf "\n"
    echo "Помните, вы можете проверить ваш инвентарь:"
    printf "\n"
    echo 'echo $I'
    printf "\n"
else
    echo "Это сокровище уже взято."
fi







































































































































































































































































































































# Hmm, that didn't work.
# Remember, when files end in a *
# it means they are applications.
# Try this:
#
# ./treasure
